ooyala/html5-video-plugins

- src/osmf/lib/HDSPlayer.as
The code to allow insecure domain has been added as http page (i.e http://debug.ooyala.com)  embeds and tries to access secure https swf. The code has been added to allow all insecure domains as the player will be hosted on multiple customer's website which will be on separate domains.
> [PBF-483] Fix for supporting HTTPS steam in OSMF player

- src/osmf/js/osmf_flash.js
[`getElementsByTagName`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName) returns an array-like object that is better traversed using a regular for loop, rather than a for-in one. This eliminates some weird errors for properties trying to be accessed in the for-in loop, such as `length`.
I honestly couldn't get the tests running, could someone please run them locally before merging?
> Change for-in loop to a normal for

- src/osmf/lib/HDSPlayer.as
Event object's duration should be set to totalTime, which is zero in case of non-seakable (live) media.  Skin expects zero duration for non-seekable media.
> [PBF-639][Flash] Live stream scrubber pointer is displayed at initial point

- .gitignore
- build_flash.xml
Delete auto-generated library before compile starts, otherwise link error of multple class definition will happen if this library is present from previous build
> [fix-osmf-build] Dele auto-generated library before compile starts

- src/main/js/main_html5.js
Adds a condition to check if the textTrack for the video element has a
src associated with it.
> [PBW-4457] CC button always showing in Safari

- src/main/js/main_html5.js
This reverts commit bfc1c6ef3718b25cd4f21a9d0350c759fa3a8798.
It is not a correct way to check for undefined.  Should be either 'a != undefined', or, better 'typeof a != "undefined"'
> Revert "[PBW-4457] CC button always showing in Safari"

- src/akamai/js/akamaiHD_flash.js
- src/main/js/main_html5.js
- src/osmf/js/osmf_flash.js
- tests/unit/main_html5/wrapper-api-tests.js
* Also allow setting initial time if video has ended
* Updated unit tests
> [PBW-5567] Seeking is ignored from video end screen, it always plays from the beginning

- src/main/js/main_html5.js
-workaround of an IE/Edge issue where setting a video src to an empty string has the side effect of a network request to the base URL of the page
> [PBW-5865]

- src/main/js/main_html5.js
So this turned out to be a bug on Safari itself (iOS and Desktop). It can be reproduced with a raw HLS stream without even using V4. It's not necessary to share the video in order to trigger the bug, all that is needed is that you switch to a different tab after the video has ended.
My guess is that Safari unloads some resources in order to save some memory when you switch tabs. When you switch back to the original tab, Safari again calculates either `currentTime` or `duration` (or both), but gets it wrong. When replay is triggered at this point, there are technically a few milliseconds left of playback, so the video plays until the end instead of restarting.
The workaround is simply to allow setting an `initialTime` of 0 on iOS (this affects both iPad and iPhone btw) and desktop Safari. …
> [PBW-5539] - Allowing initialTime of 0 on Safari as a workaround for browser bug

- src/main/js/main_html5.js
- tests/unit/main_html5/factory-tests.js
This issue was caused by Safari stopping playback without firing a `pause` event when a new tab is focused. The player never finds out that the video is paused and it gets stuck in buffering state. After trying a lot of ugly workarounds, I noticed that this only happens when `preload` is set to `none`.
I spent some time looking for potential problems caused by switching `preload` to `metadata` on Safari, but I couldn't find any. The main side-effects of this are that `onLoadedMetadata` is fired earlier than usual and that `this.load` might not be called during `executePlay`. I checked the code and this seems to be ok, but please let me know in case I'm missing something.
> [PBW-5470] - Setting preload to 'metadata' on desktop Safari

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
- tests/unit/main_html5/wrapper-event-tests.js
* Special cases for Safari and Edge to set closed captions for live video
* Don't add text tracks for VOD on Safari or Edge
* Updated unit tests
> [PBW-6077][EDGE][MAIN_HTML5] CC-live module not registering live HLS stream CC

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
- tests/unit/main_html5/wrapper-event-tests.js
* Fixes in setClosedCaptions:
** Do not remove text tracks unless language is null
** Remove text tracks before setting new ones if they are different from to-be added, otherwise we may see native closed captions
** Create new text tracks only if they don't exist
* Do not remove text tracks if CC mode is disabled, setting text tracks mode to disabled is efficient.
* Updated unit tests
> [PBW-6127] Avoiding duplicate CCs (native + external ones) and making sure we add new text tracks only when required

- src/main/js/main_html5.js
Removed duplicate videoEnded=false that was confusing player on replay. videoEnded=false remain in exeuctePlay where it belongs.
> [PBW-4456] Removed duplicate videoEnded=false that was confusing replay

- src/main/js/main_html5.js
- tests/unit/main_html5/underflow-tests.js
- tests/unit/main_html5/wrapper-event-tests.js
[Link to ticket](https://jira.corp.ooyala.com/browse/PBW-6200)
The problem was caused by the fact that MS Edge doesn't trigger `playing` or `canplaythrough` after seeking ([example](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6168727/)), so the buffering state was not being reset. It's also worth noting that `canplaythrough` [isn't properly implemented on all browsers](https://bugs.chromium.org/p/chromium/issues/detail?id=73609), so it's probably better not to rely on it too much. 
The `playing` event seemed like a good place to raise the `BUFFERED` event, but according to the spec, it is not necessarily supposed to be fired after seeking. This means that the only way to determine whether the video has resumed after buffering is to check that `currentTime` is …
> [PBW-6200] - Fixes stuck loading spinner on Edge

- src/youtube/js/youtube.js
* When plugin was destroyed, setInterval was still generating TIME_UPDATE events for stale instance of VTC (which is supposed to be garbage-collected at some point, but it didn't because it was still being used).  This orphaned VTC object was trying to obtain isLive property from non-existing active instance in order to publish PLAYHEAD_TIME_CHANGED events for skin, which resulted in numerous JS exceptions.  Fix is to clear this interval when plugin is being disposed.
> [PBW-6266]Problem switching between a number of videos on the same page

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
[Link to ticket](https://jira.corp.ooyala.com/browse/PLAYER-212)
Continuous playback on mobile requires that the same video element be used for all videos, otherwise a user gesture would be required to initiate playback on each one. I made some changes to the core in order to recycle the video element, but this caused closed captions to reappear on new videos because the text tracks hadn't been cleared.
I updated *main_html5* so that the captions are cleared when a new video is set, with the assumption that we no longer need the captions from the previous video. This appears to be working  fine, but please let me know in case I'm missing something here.
Related PR's:
https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/168
https://github.com/ooyala/html5-skin/pull/704
> [PLAYER-212] - Clearing closed captions when new video is set

- src/main/js/main_html5.js
- tests/utils/test_lib.js
Related tickets:
[PLAYER-327](https://jira.corp.ooyala.com/browse/PLAYER-327)
[PLAYER-73](https://jira.corp.ooyala.com/browse/PLAYER-73)
Possibly also: [PBW-5682](https://jira.corp.ooyala.com:8443/browse/PBW-5682) 
It looks like this is a bug in Safari that is possibly triggered by adding and removing tracks, although I couldn't really find a good explanation for the cause. There are two main problems that can be observed in Safari:
- Even though _Track_ elements are successfully removed, every now and then the corresponding _TextTrack_ object will remain, and it will get duplicated once a new one is added. This is usually not a problem in itself since the code already has logic that disables  previous tracks though.
- For some reason Safari will randomly choose to change the mode of a …
> [PLAYER-327][PLAYER-73] -Workaround for duplicate CC's

- src/main/js/main_html5.js
We need this in order to access `OO.getRandomString`
> [PLAYER-327] - Added missing require statement

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
- Added `preload=auto` to the video element in order allow preloading the full content when available
- Fixed an issue where playback would freeze when priming a video on iOS with preloading on.
> [PLAYER-1323] Video preloading fixes

- src/osmf/js/osmf_flash.js
To get cleaner console output; this is almost certainly not a fatal error, unless there is no other video plugin included.
> Rather than a console error, simply log if Flash is not detected

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
- tests/unit/main_html5/wrapper-event-tests.js
- tests/utils/mock_vtc.js
-updated html5-common subrepo
-main_html5 will now notify of the MUTE_STATE_CHANGE event
-main_html5 will no longer unmute on a volume change
-new unit tests for the MUTE_STATE_CHANGE event
> [player-1897]

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
There's a strange bug in Safari on iOS11 that causes CORS errors to be  incorrectly thrown when setting the `crossorigin` attribute after a video has played without it. This usually happens when a video with CC's is played after a preroll that's not using `crossorigin`.
For some reason it seems that Safari is not enforcing same origin policy for VTT files, so at least for now it seems that it's safe to just prevent Safari from setting the `crossorigin` attribute at all.
> [PBW-6882] Workaround for Safari CORS issues on iOS 11

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
- tests/unit/main_html5/wrapper-event-tests.js
-main html5 will now notify of MUTE_STATE_CHANGE based on the videos muted attribute rather than pulling from the event
-main html5 will raise volume event when the mute or unmute APIs are called since the volumechange event does not always seem to get fired by the browser
> [player-1788b]

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
-we will now restore the last known volume when unmuting in the main_html5 plugin
> [player-2438]

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
-we will now attempt to check if a play promise error is a user interaction required error before throwing UNMUTED_PLAYBACK_FAILED
> [player-2445]

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
- tests/unit/main_html5/wrapper-event-tests.js
These changes will enable DVR functionality on browsers that can play HLS natively:
- Safari
- iOS  Safari
- MS Edge
Android Chrome doesn't support DVR yet, but if support is added later on these changes should work out of the box.
> [PLAYER-404] Add DVR support to MainHtml5

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
The playhead is updated after pausing and resuming a DVR-enabled stream in order to reflect that you moved away from the live playhead. This was causing the playhead position to be set to a negative value and overflow if you paused the video for a time longer than the DVR window.
> [PLAYER-404] Fix for playhead overflowing when DVR stream is paused for a long time

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
[PBW-6990](https://jira.corp.ooyala.com/browse/PBW-6990)
It looks like there's a random Android bug that causes muted autoplay to fail in general even with [Chrome's muted autoplay samples](https://googlechrome.github.io/samples/muted-autoplay/). 
This workaround will basically fire the `PLAYING` and `PAUSED` events in order to force the player out its initial loading state and show the control bar so that the user can resume manually. A cleaner approach might be to set the player back to its initial state, however, we don't have any logic to reset the player without changing the embed code yet, so this would be more complicated and risky.
If we're ok with this approach we will need to implement something similar for BitWrapper as well.
> [PBW-6990] Workaround that allows manual playback when muted autoplay is not possible

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
- tests/utils/mock_vtc.js
-changes to make use of a new MUTED_AUTOPLAY_FAILED notification. Moved current muted autoplay failure workaround to the VTC
> [player-2700]

- src/akamai/js/akamaiHD_flash.js
- src/osmf/js/osmf_flash.js
Super simple workaround that hard codes the path to the .swf file (for OSMF and Akamai plugins) when it can't be obtained from the script tag. The reasoning is that we're no longer updating these plugins so it's safe to use a static file location.
These plugins don't have unit tests.
> [PLAYER-3129] Workaround for .swf files not being found when using Valhalla

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-event-tests.js
-we will now use onvolumechange to listen for volume/mute state changes with main_html5. This allows us to maintain a more accurate state for us and external SDKs such as Freewheel
-removed volumechangeNew as it was not in use and is not a real event
> [player-3192]

- tests/utils/test_lib.js
`InitOOJQuery` will be deprecated. See comments on main PR:
https://github.com/ooyala/html5-ad-plugins/pull/247
> [PLAYER-2104] Removing reference to InitOOJQuery

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-event-tests.js
-fixed an issue where VTC does not get notified of a MULTI_AUDIO_CHANGED event when switching streams with the same available audio as the first
> [player-3419]

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-event-tests.js
-fixed an issue where the VTC PLAYING notification was not sent out if a play was queued due to a seek (typically happens on replay)
> [player-3577]

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-event-tests.js
-fixed an issue where playing notifications were not sent to vtc if the playing event was triggered from something other than a play promise in an environment where play promises are supported
> [player-3792]

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
- tests/unit/main_html5/wrapper-event-tests.js
MainHtml5 is currently only able to handle a single in-manifest/in-stream text track. This is a workaround that enables displaying and selecting multiple in-manifest/in-stream text tracks.
> [PLAYER-4150] Allowing multiple in-manifest/in-stream captions

- src/main/js/main_html5.js
- tests/unit/main_html5/factory-tests.js
Don't merge until html5-common is updated with the new constants
> Player 4169

- .babelrc
- package-lock.json
- package.json
- src/main/js/constants/constants.js
- src/main/js/main_html5.js
- src/main/js/text_track/text_track_helper.js
- src/main/js/text_track/text_track_map.js
- tests/setup.js
- tests/unit/main_html5/wrapper-api-tests.js
- tests/unit/main_html5/wrapper-event-tests.js
Rewrote most of the closed captions implementation from scratch. The main issues that were addressed by these changes are the following:
- Allowing captions to be switched via the native fullscreen UI on iOS
- Allowing captions to be turned off via the native fullscreen UI on iOS
- Keeping the player's UI in sync with the native fullscreen UI on iOS
These changes will also fix the following:
- In-manifest/In-stream captions for VOD will now be available on supported platforms
- Metadata text tracks will no longer show up in the UI
- Text tracks will no longer be removed and re-added on each call to `setClosedCaptions`
- VTT files will no longer be requested on each call to `setClosedCaptions` and when pausing and then resuming
- More robust handling of multi closed captions for live …
> [PLAYER-4216] (PR 3 of 3) MainHtml5 closed captions refactor

- src/main/js/main_html5.js
Skipping unit tests to get this into tonight's build for QA testing, will add tests later
> [PLAYER-4422] changes to seek to previous position in dvr window on failover for live

- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-event-tests.js
We have some code in the core which clears the current video stream by setting an empty source before a new source is loaded. On iOS Safari this was causing the `ended` event to be triggered when the source was cleared, which in turn caused the player to display the end screen when a new video was loaded.
> [PLAYER-4264] Fix for continuous playback on mobile browsers

- src/main/js/main_html5.js
This is a potential fix for the https://jira.corp.ooyala.com/browse/PBW-7648.
I have also tried to put this pause in `then` of `playPromise` and it just stops after start of the playing so it seems to me that it is pointless here.
Unit tests passed.
> Removed the video pause call from primeVideoElement

- README.md
- ant-builds.js
- package-lock.json
- package.json
- webpack.config.js
https://jira.corp.ooyala.com/browse/PLAYER-4906
> Inject webpack into html5_video_plugin repo

- package.json
- src/main/js/main_html5.js
- tests/unit/main_html5/wrapper-api-tests.js
airplay icon is not displayed as expected with discovery and playlists
[Jira ticket](https://jira.corp.ooyala.com/browse/PLAYER-5365)
[Related Core PR](https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/658/overview)
in Safari (for both MacOS and iOS) 
```javascript
video.src = null;
```
leads to (for example) video.**src** === 'debug.ooyala.com/ea/**null**'
This issue was resolved for iOS like that
```javascript
delete _video.src
```
Added similar workaround for MacOS since delete doesn't work here:
```jacascript
_video.removeAttrribute('src');
```
will set _video.src to ' ' (empty string) 
```javascript
_video.load()
```
to reset the video (video 'loadstart' and airplay 'playbackTargetChanged' events won't be fired that way)
> Player 5365 airplay icon bug with discovery and playlists

- src/main/js/main_html5.js
Discovered that MS Edge browser for the specific mp4 assets fires `ended` event with `undefined` data provided right in the beginning of the playback. Added this into the list of conditions to be ignored.
> [PBW-7937] fake _ended_ event for some mp4 assets in MS Edge now ignored

- src/main/js/main_html5.js
TS requested this attribute to be added on MacOS, not only IOS. Done.
To confirm checked that Bitmovin doing the same for desktop browsers.
> [PBW-8033] playsinline attribute now added in desktop as well

- src/main/js/main_html5.js
The issue is that when customer accidentally or in purpose adds both main and bitmovin plugin to their implementation, main plugin will try to play audio_hls in cases where it shouldn't have like Android Chrome. This should only be played with Bitmovin plugin.
This fix consists in removing audio_hls supported encoding in Android Chrome.
> [PBW-7936] Audio player not working on Android 9
