src/main/js/main_html5.js, src/template.js, tests/unit/main_html5/wrapper-api-tests.js, tests/unit/main_html5/wrapper-event-tests.js
Associated with:
https://github.com/ooyala/html5-ad-plugins/pull/48
https://github.com/ooyala/html5-common/pull/20
And two internal pull requests
=> [PBW-2677] Add function to prime video elements

src/osmf/lib/DynamicEvent.as, src/osmf/lib/ExternalJavaScriptAPI.as, src/osmf/lib/HDSPlayer.as
Full screen is handled by skin and hence removing full screen
implementation.
=> Removing full screen implementation from OSMF Flash plugin

src/osmf/js/osmf_flash.js
=> [PBF-488] Added scale property to fix video resize issue

src/main/js/main_html5.js
This depends on https://github.com/ooyala/html5-common/pull/27 and might need to be updated if that CR needs changing
=> [PBW-4472] Do not report support for web on edge or ie

src/osmf/js/osmf_flash.js, src/osmf/lib/HDSPlayer.as
Resizes OSMF video based on video container size. Also repositions
closed captions (PBF-509) based on responsive-design width breakpoints
to rest above height of control bar.
=> [PBF-508] Responsive resize the OSMF video

src/osmf/js/osmf_flash.js, src/osmf/lib/DynamicEvent.as, src/osmf/lib/ExternalJavaScriptAPI.as, src/osmf/lib/HDSPlayer.as
Sends events with asset dimensions to VTC on resize.
Also cleans up console logs.
=> [PBF-506] Notify VTC of asset's dimension

src/osmf/js/osmf_flash.js
Fixes OSMF to be able to run with the CMS-less player
=> [PBW-4330] CMSless player for OSMF

src/osmf/js/osmf_flash.js, src/osmf/lib/DynamicEvent.as, src/osmf/lib/ExternalJavaScriptAPI.as, src/osmf/lib/HDSPlayer.as
Pull request for FCC captions.
@angieisrani / @aldigun, please review. We need to get this into this release.
@nagavenivn, @sarita-ooyala, @prachiagarwal, FYI...
=> PBF-597: OSMF: make sure plugin support cueChange and CC hidden mode

src/main/js/main_html5.js, tests/unit/main_html5/wrapper-api-tests.js
* Fixing infinite playing event loop that happens with API seek calls for HLS assets on iOS
* Updated unit tests
=> [PBW-5360] [PV4] Mid Rolls not working in DFP Mobile

src/main/js/main_html5.js
Despite comments about the commit. Moving this to a pull request so it can be better tracked if it needs to be edited or if it is found to be mergable.
See comment history in the commit before making any decision to merge this.
=> [PBW-4409] Manually raise TIME_UPDATE event on seek from pause to address Firefox

src/akamai/js/akamaiHD_flash.js, src/akamai/lib/AkamaiEdgeAuthTokenAuthorizer.as, src/akamai/lib/AkamaiHDPlayer.as, src/akamai/lib/ExternalJavaScriptAPI.as, src/akamai/lib/LoggingEventDispatcher.as
Added feature for Secure Token support
=> PBF-647: Akamai Secure Token

src/main/js/main_html5.js, src/template.js
Added onAdsPlayed placeholder public method
=> [PBW-4530] After skipping a postroll, control bar on end screen showposition of ad when it was skipped

src/akamai/js/akamaiHD_flash.js
Adds encoding for Akamai live/remote for secure tokens.
See pull requests in:
mjolnir
html5-common
html5-video-plugins
=> [PBF-661] Adds encoding for Akamai live/remote for secure tokens.

src/akamai/js/akamaiHD_flash.js, src/osmf/js/osmf_flash.js
Change to get Telstra signing to work.
=> PBF-669: Telstra signing not working

src/akamai/js/akamaiHD_flash.js, src/main/js/main_html5.js, src/osmf/js/osmf_flash.js, src/osmf/lib/ExternalJavaScriptAPI.as, src/osmf/lib/HDSPlayer.as, src/template.js
Reverting back PBF-662 changes and adding documentation as per PBW-5703
=> PBF 662 revert

src/akamai/lib/AkamaiHDPlayer.as
Fix for Blizzcon to read the CC in the format sent by them.
=> Fix for reading Live CC

src/akamai/lib/AkamaiHDPlayer.as
and allow Akamai to set the alignment on the stage
=> PBF-719 : Remove stage align property

src/main/js/main_html5.js
Reverts ooyala/html5-video-plugins#216
=> Revert "[PBW-4456] Removed duplicate videoEnded=false that was confusing replay"

src/youtube/js/youtube.js, tests/unit/youtube/factory-tests.js
⚠️  must be merged with - https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/154/overview
=> PBF-731 : Support Mixed discovery content with Youtube

src/main/js/main_html5.js, src/template.js, tests/unit/main_html5/wrapper-api-tests.js, tests/unit/main_html5/wrapper-event-tests.js
Muted autoplay
-added mute and unmute functions to main_html5 and the template
-added new function ‘requiresMutedAutoplay’ to main_html5 and template
=> Player 1788

src/template.js
-introduced a new muteState argument for the setVolume API
=> [player-1788]

src/osmf/js/osmf_flash.js
-implemented mute states in the osmf flash plugin
-there are no unit tests for osmf, unfortunately
=> [player-2026]

src/main/js/main_html5.js, src/template.js, tests/unit/main_html5/wrapper-api-tests.js, tests/utils/mock_vtc.js
New muted autoplay flow using video element promises
=> Player 2194

src/main/js/main_html5.js, src/template.js, tests/unit/main_html5/wrapper-api-tests.js, tests/utils/mock_vtc.js
New function added that sets audio track in accordance with specified trackID.
Unit tests added.
Unit tests were run without errors.
=> [PLAYER-2947] dev-epam to mater

tests/unit/main_html5/wrapper-event-tests.js
-fix a unit test broken by recent volumechange change
=> [fix-unit-tests]

src/main/js/main_html5.js, src/template.js, tests/unit/main_html5/wrapper-api-tests.js, tests/unit/main_html5/wrapper-event-tests.js, tests/utils/mock_vtc.js
=> Player 2103

src/main/js/main_html5.js, src/template.js, tests/unit/main_html5/wrapper-api-tests.js
=> [player-3596]

src/main/js/main_html5.js, tests/unit/main_html5/wrapper-api-tests.js, tests/unit/main_html5/wrapper-event-tests.js
-fixed an issue where main_html5 would play a little of the content before seeking back to the beginning
=> [player-3725]

src/main/js/main_html5.js, tests/unit/main_html5/wrapper-event-tests.js
-fixed an issue where we could seek to a time multiple times if a queued seek is equal to the current time of the video
=> [player-3904]

src/main/js/main_html5.js, tests/unit/main_html5/wrapper-api-tests.js
-removed player dimension tracking and custom iPad CSS from main_html5
=> [player-4073]

gulpfile.js
=> [player-4161]

src/main/js/main_html5.js, tests/unit/main_html5/wrapper-event-tests.js
-workaround of an issue where we lose an initial time seek for a live stream where DVR is not available yet
=> [player-4444] - Initial time for Live DVR

Jenkinsfile, package.json, sonar-project.properties
Added package.json commands (dummy for now) to unblock devops
=> Added package.json commands (dummy for now) to unblock devops

README.md
=> [PLAYER-5575] Update submodule
